/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
export declare function getPdfText(fileData: Uint8Array): string
export declare function getPdfPwText(fileData: Uint8Array, password: string): string
